# Process Path Exploration and QA
A process path is defined here as a list of processes from the current to the root.

## Setup
Download data from https://gdo-wintap.llnl.gov

A good starting set is: https://gdo168.llnl.gov/data/ACME-2023/stdview-20231105-20231120/process_path.parquet

If you'd like more data, look into the longer date ranges.

Modify the path in the "create view" statement to point to where you have downloaded the process_summary.parquet file.

In [2]:
# Import packages used in notebooks
import altair as alt
import duckdb
import pandas as pd
%load_ext magic_duckdb

pd.set_option('display.max_rows', 200)

In [3]:
# Initialize an in-memory db. Save reference in a variable and then set magic-duckdb environment. Result is ability to use the same DB instance from python code and %dql/%%dql magics.
con = duckdb.connect()
%dql -co con
# Only uses a process_path table
%dql create view process_path as from '~/data/wintapv6/ACME-Redo/stdview-20231105-20231120/process_path.parquet'
# Display a simple summary of the table
%dql summarize process_path

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,agent_id,VARCHAR,None,None,0,None,None,None,None,None,4707705,100.00
1,hostname,VARCHAR,ACME-DC1,ACME-WS-UVF,23,None,None,None,None,None,4707705,0.00
2,pid_hash,VARCHAR,00000016049E7D08D555AA56CD072E2F,FFFFFB83788869D71024896A7A0AB5E3,5127288,None,None,None,None,None,4707705,0.00
3,os_pid,INTEGER,0,17404,3997,5881.477275020418,3749.8624803398047,3141,5072,7983,4707705,0.00
4,process_name,VARCHAR,/powershell.exe,xmlcatalog.exe,640,None,None,None,None,None,4707705,1.88
5,process_path,VARCHAR,%systemroot%\system32\csrss.exe,wlrmdr.exe,2030,None,None,None,None,None,4707705,1.88
6,level,INTEGER,0,448,482,6.242456356122569,4.700774239759703,6,6,7,4707705,0.00
7,parent_pid_hash,VARCHAR,0004A3028DF9B41A327607921D373D28,FFB335D887A9496741C2E609899391BB,391,None,None,None,None,None,4707705,1.89
8,parent_os_pid,INTEGER,4,11728,284,283.65467104382833,548.9178043348807,4,4,614,4707705,1.89
9,seq,INTEGER,1,449,499,7.242456356122569,4.700774239759703,7,7,8,4707705,0.00
10,ptree,VARCHAR,=/powershell.exe->ruby.exe->vagrant.exe->power...,=xmlcatalog.exe->bash.exe->bash.exe->cmd.exe->...,4344,None,None,None,None,None,4707705,1.89
11,ptree_list,VARCHAR[],"[00000016049E7D08D555AA56CD072E2F, 6303B1F691A...","[FFFFFB83788869D71024896A7A0AB5E3, 9AF962CF4BC...",4348300,None,None,None,None,None,4707705,0.00
12,ptree_list_tuples,"STRUCT(pid_hash VARCHAR, process_name VARCHAR)[]",[{'pid_hash': 00000016049E7D08D555AA56CD072E2F...,[{'pid_hash': FFFFFB83788869D71024896A7A0AB5E3...,5037409,None,None,None,None,None,4707705,0.00
13,max_level,INTEGER,0,448,482,6.242456356122569,4.700774239759703,6,6,7,4707705,0.00

# Process Paths: Initial EDA
Build a base SQL view that parses the path structure. This just simplifies the queries after this point.

Features:
* root_process_name
* root_pid_hash
* parent_process_name
* grand_parent_process_name
* great_grand_parent_process_name

In [4]:
%%dql
create or replace view process_path_root
as
select
	*,
	ptree_list_tuples[-1:][1]['process_name'] root_process_name,
	ptree_list_tuples[-1:][1]['pid_hash'] root_pid_hash,
	ptree_list_tuples[2:2][1]['process_name'] parent_process_name,
	ptree_list_tuples[2:2][1]['pid_hash'] parent_pid_hash,
	ptree_list_tuples[3:3][1]['process_name'] grand_parent_process_name,
	ptree_list_tuples[3:3][1]['pid_hash'] grand_parent_pid_hash,
	ptree_list_tuples[4:4][1]['process_name'] great_grand_parent_process_name,
	ptree_list_tuples[4:4][1]['pid_hash'] great_grand_parent_pid_hash
from
	process_path

Empty DataFrame
Columns: [Count]
Index: []

In [5]:
%%dql
-- What are the roots? They *should* all be ntoskrnl.exe
select
	root_process_name,
	count(distinct hostname) num_hosts,
	count(distinct root_pid_hash) uniq_root_pid_hash,
	median(level) median_path_depth,
	max(level) max_path_depth,
	count(*) num_process
from
	process_path_root
group by all
order by num_hosts

,root_process_name,num_hosts,uniq_root_pid_hash,median_path_depth,max_path_depth,num_process
0,cmd.exe,1,155,155.0,448,1987
1,devenv.exe,1,1,8.0,20,1243
2,searchapp.exe,1,1,4.0,5,875
3,vshost.exe,1,1,7.0,9,411
4,shellexperiencehost.exe,1,1,5.0,10,666
5,taskkill.exe,1,1,0.0,0,1
6,msedge.exe,1,2,5.0,6,222
7,vcpkgsrv.exe,1,1,6.0,6,45
8,wmiprvse.exe,2,2,5.0,7,119
9,logonui.exe,2,2,5.0,6,70
10,dwm.exe,2,2,2.0,2,6
11,explorer.exe,2,2,4.5,5,2
12,userinit.exe,2,2,5.5,6,22
13,winlogon.exe,5,6,2.0,6,11
14,svchost.exe,5,5,6.0,67,1143725
15,wintap.exe,6,6,6.0,11,392427
16,conhost.exe,7,171,0.0,4,171
17,mergehelper.exe,7,7,5.0,8,85107
18,services.exe,11,11,4.0,5,33
19,wininit.exe,11,11,4.0,5,23
20,None,22,88465,0.0,2,89187
21,ntoskrnl.exe,26,60,7.0,127,2991352

In [6]:
%%dql
-- What happens if we remove mergehelper and wintap?
select
	root_process_name,
	count(distinct hostname) num_hosts,
	count(distinct root_pid_hash) uniq_root_pid_hash,
	median(level) median_path_depth,
	max(level) max_path_depth,
	count(*) num_process
from
	process_path_root
    where process_name not in ('mergehelper.exe','wintap.exe')
group by all
order by num_hosts

,root_process_name,num_hosts,uniq_root_pid_hash,median_path_depth,max_path_depth,num_process
0,cmd.exe,1,155,155.0,448,1987
1,vshost.exe,1,1,7.0,9,411
2,searchapp.exe,1,1,4.0,5,875
3,devenv.exe,1,1,8.0,20,1243
4,shellexperiencehost.exe,1,1,5.0,10,666
5,msedge.exe,1,2,5.0,6,222
6,vcpkgsrv.exe,1,1,6.0,6,45
7,taskkill.exe,1,1,0.0,0,1
8,userinit.exe,2,2,5.5,6,22
9,logonui.exe,2,2,5.0,6,70
10,explorer.exe,2,2,4.5,5,2
11,dwm.exe,2,2,2.0,2,6
12,wmiprvse.exe,2,2,5.0,7,119
13,svchost.exe,5,5,6.0,67,606597
14,winlogon.exe,5,6,2.0,6,11
15,conhost.exe,6,170,0.0,4,170
16,wintap.exe,6,6,6.0,11,229839
17,mergehelper.exe,7,7,5.0,8,42549
18,wininit.exe,11,11,4.0,5,17
19,services.exe,11,11,4.0,5,33
20,None,22,711,1.0,2,722
21,ntoskrnl.exe,26,60,7.0,127,1703699

In [7]:
%%dql
-- What are the roots? They *should* all be ntoskrnl.exe
select *, 
   	-- Calculate percent for host and rank within host
	RANK() OVER (PARTITION BY hostname ORDER BY num_process DESC) rank_pos,
    round((num_process/sum(num_process) OVER (PARTITION BY hostname))*100,2) root_process_name_pct
from (
	select
		hostname, 
		root_process_name,
		count(distinct root_pid_hash) uniq_root_pid_hash,
		median(level) median_path_depth,
		max(level) max_path_depth,
		count(*) num_process,
	from
		process_path_root
	group by all)
order by hostname, num_process

,hostname,root_process_name,uniq_root_pid_hash,median_path_depth,max_path_depth,num_process,rank_pos,root_process_name_pct
0,ACME-DC1,wininit.exe,1,2.5,3,2,6,0.00
1,ACME-DC1,services.exe,1,3.0,3,3,5,0.00
2,ACME-DC1,ntoskrnl.exe,1,10.0,127,1529,4,0.83
3,ACME-DC1,cmd.exe,155,155.0,448,1987,3,1.08
4,ACME-DC1,None,4429,0.0,1,4433,2,2.42
5,ACME-DC1,svchost.exe,1,5.0,67,175410,1,95.66
6,ACME-HH-AKA,conhost.exe,1,0.0,0,1,5,0.00
7,ACME-HH-AKA,winlogon.exe,1,1.5,2,2,4,0.00
8,ACME-HH-AKA,logonui.exe,1,2.0,2,3,3,0.00
9,ACME-HH-AKA,None,2657,0.0,1,2665,2,1.99
10,ACME-HH-AKA,ntoskrnl.exe,12,7.0,17,130923,1,98.00
11,ACME-HH-ATV,wininit.exe,1,3.5,4,2,6,NaN
12,ACME-HH-ATV,services.exe,1,4.0,4,3,5,NaN
13,ACME-HH-ATV,wintap.exe,1,6.0,7,2366,4,NaN
14,ACME-HH-ATV,None,2874,0.0,1,2882,3,NaN
15,ACME-HH-ATV,mergehelper.exe,1,4.0,5,13718,2,NaN
16,ACME-HH-ATV,ntoskrnl.exe,5,7.0,16,95993,1,NaN
17,ACME-HH-AXF,winlogon.exe,1,1.0,1,1,4,0.00
18,ACME-HH-AXF,dwm.exe,1,2.0,2,3,3,0.00
19,ACME-HH-AXF,None,3516,0.0,1,3552,2,2.48
20,ACME-HH-AXF,ntoskrnl.exe,3,7.0,8,139678,1,97.52
21,ACME-HH-AZH,None,4751,0.0,1,4783,2,2.70
22,ACME-HH-AZH,ntoskrnl.exe,3,7.0,12,172558,1,97.30
23,ACME-HH-BVW,wininit.exe,1,4.0,4,3,5,0.00
24,ACME-HH-BVW,services.exe,1,4.0,4,3,5,0.00
25,ACME-HH-BVW,None,3842,0.0,1,3874,4,2.29
26,ACME-HH-BVW,ntoskrnl.exe,1,13.0,16,3920,3,2.32
27,ACME-HH-BVW,mergehelper.exe,1,4.0,5,15719,2,9.29
28,ACME-HH-BVW,wintap.exe,1,6.0,11,145594,1,86.09
29,ACME-HH-CCF,None,3308,0.0,1,3312,2,2.26
30,ACME-HH-CCF,ntoskrnl.exe,1,7.0,18,143322,1,97.74
31,ACME-HH-CIH,conhost.exe,1,4.0,4,1,7,0.00
32,ACME-HH-CIH,wininit.exe,1,4.5,5,2,6,0.00
33,ACME-HH-CIH,services.exe,1,5.0,5,3,5,0.00
34,ACME-HH-CIH,ntoskrnl.exe,1,1.0,2,7,4,0.01
35,ACME-HH-CIH,None,3322,0.0,1,3360,3,2.46
36,ACME-HH-CIH,mergehelper.exe,1,6.0,8,22410,2,16.43
37,ACME-HH-CIH,wintap.exe,1,7.0,8,110627,1,81.10
38,ACME-HH-CLR,None,1641,0.0,1,1658,2,NaN
39,ACME-HH-CLR,ntoskrnl.exe,1,7.0,14,65828,1,NaN
40,ACME-HH-DFN,None,3839,0.0,1,3881,2,2.61
41,ACME-HH-DFN,ntoskrnl.exe,1,7.0,10,145002,1,97.39
42,ACME-HH-EAY,None,3868,0.0,1,3878,2,2.50
43,ACME-HH-EAY,ntoskrnl.exe,3,7.0,14,151003,1,97.50
44,ACME-HH-HGC,winlogon.exe,1,1.5,2,2,4,0.00
45,ACME-HH-HGC,logonui.exe,1,5.0,6,67,3,0.05
46,ACME-HH-HGC,None,3310,0.0,1,3345,2,2.32
47,ACME-HH-HGC,ntoskrnl.exe,3,7.0,9,140635,1,97.63
48,ACME-HH-IKA,explorer.exe,1,5.0,5,1,12,0.00
49,ACME-HH-IKA,wininit.exe,1,3.5,4,2,10,0.00
50,ACME-HH-IKA,winlogon.exe,1,5.5,6,2,10,0.00
51,ACME-HH-IKA,services.exe,1,4.0,4,3,9,0.00
52,ACME-HH-IKA,userinit.exe,1,6.0,6,12,8,0.01
53,ACME-HH-IKA,vcpkgsrv.exe,1,6.0,6,45,7,0.03
54,ACME-HH-IKA,vshost.exe,1,7.0,9,411,6,0.24
55,ACME-HH-IKA,devenv.exe,1,8.0,20,1243,5,0.72
56,ACME-HH-IKA,mergehelper.exe,1,4.0,5,3635,4,2.10
57,ACME-HH-IKA,None,4710,0.0,1,4749,3,2.75
58,ACME-HH-IKA,wintap.exe,1,6.0,7,12932,2,7.48
59,ACME-HH-IKA,ntoskrnl.exe,3,7.0,11,149853,1,86.68
60,ACME-HH-IQS,None,4289,0.0,1,4332,2,2.46
61,ACME-HH-IQS,ntoskrnl.exe,3,7.0,14,171771,1,97.54
62,ACME-HH-KKN,services.exe,1,4.0,4,3,5,0.00
63,ACME-HH-KKN,wininit.exe,1,4.0,4,3,5,0.00
64,ACME-HH-KKN,wintap.exe,1,6.0,7,2321,4,1.59
65,ACME-HH-KKN,None,4032,0.0,1,4067,3,2.78
66,ACME-HH-KKN,mergehelper.exe,1,4.0,5,14738,2,10.09
67,ACME-HH-KKN,ntoskrnl.exe,3,7.0,14,124987,1,85.54
68,ACME-HH-MBY,conhost.exe,1,0.0,0,1,10,0.00
69,ACME-HH-MBY,explorer.exe,1,4.0,4,1,10,0.00
70,ACME-HH-MBY,wininit.exe,1,3.0,3,1,10,0.00
71,ACME-HH-MBY,dwm.exe,1,2.0,2,3,8,0.00
72,ACME-HH-MBY,services.exe,1,4.0,4,3,8,0.00
73,ACME-HH-MBY,winlogon.exe,2,3.0,5,4,7,0.00
74,ACME-HH-MBY,userinit.exe,1,5.0,5,10,6,0.01
75,ACME-HH-MBY,wmiprvse.exe,1,4.0,4,58,5,0.04
76,ACME-HH-MBY,msedge.exe,2,5.0,6,222,4,0.15
77,ACME-HH-MBY,None,3364,0.0,1,3391,3,2.24
78,ACME-HH-MBY,svchost.exe,1,6.0,7,17052,2,11.28
79,ACME-HH-MBY,ntoskrnl.exe,4,7.0,10,130438,1,86.28
80,ACME-HH-OLY,None,3355,0.0,1,3383,2,2.47
81,ACME-HH-OLY,ntoskrnl.exe,1,7.0,8,133830,1,97.53
82,ACME-HH-TON,wininit.exe,1,4.0,4,3,5,NaN
83,ACME-HH-TON,services.exe,1,4.0,4,3,5,NaN
84,ACME-HH-TON,ntoskrnl.exe,1,4.0,7,35,4,NaN
85,ACME-HH-TON,None,3200,0.0,1,3239,3,NaN
86,ACME-HH-TON,mergehelper.exe,1,4.0,5,14886,2,NaN
87,ACME-HH-TON,wintap.exe,1,6.0,7,118587,1,NaN
88,ACME-HH-TTW,None,3904,0.0,1,3938,2,2.75
89,ACME-HH-TTW,ntoskrnl.exe,1,7.0,8,139301,1,97.25
90,ACME-HH-UWI,conhost.exe,1,4.0,4,1,7,0.00
91,ACME-HH-UWI,wininit.exe,1,4.5,5,2,6,0.00
92,ACME-HH-UWI,services.exe,1,5.0,5,3,5,0.00
93,ACME-HH-UWI,wmiprvse.exe,1,5.0,7,61,4,0.04
94,ACME-HH-UWI,None,3482,0.0,1,3526,3,2.45
95,ACME-HH-UWI,svchost.exe,1,7.0,8,16866,2,11.73
96,ACME-HH-UWI,ntoskrnl.exe,3,7.0,8,123274,1,85.77
97,ACME-HH-YIM,None,3257,0.0,1,3286,2,NaN
98,ACME-HH-YIM,ntoskrnl.exe,1,7.0,9,133159,1,NaN
99,ACME-WS-AZU,ntoskrnl.exe,1,7.0,9,120915,1,100.00
100,ACME-WS-NUQ,wininit.exe,1,3.0,3,1,6,0.00
101,ACME-WS-NUQ,services.exe,1,4.0,4,3,5,0.00
102,ACME-WS-NUQ,conhost.exe,81,0.0,0,81,4,0.02
103,ACME-WS-NUQ,searchapp.exe,1,4.0,5,875,3,0.19
104,ACME-WS-NUQ,ntoskrnl.exe,1,7.0,15,1196,2,0.26
105,ACME-WS-NUQ,svchost.exe,1,6.0,12,454089,1,99.53
106,ACME-WS-PLU,taskkill.exe,1,0.0,0,1,3,0.00
107,ACME-WS-PLU,None,13515,0.0,2,13653,2,2.81
108,ACME-WS-PLU,ntoskrnl.exe,1,7.0,18,471623,1,97.19
109,ACME-WS-PRV,mergehelper.exe,1,4.0,4,1,7,0.00
110,ACME-WS-PRV,wininit.exe,1,4.5,5,2,6,0.00
111,ACME-WS-PRV,services.exe,1,5.0,5,3,5,0.00
112,ACME-WS-PRV,conhost.exe,84,0.0,0,84,4,0.02
113,ACME-WS-PRV,ntoskrnl.exe,1,7.0,17,467,3,0.10
114,ACME-WS-PRV,shellexperiencehost.exe,1,5.0,10,666,2,0.14
115,ACME-WS-PRV,svchost.exe,1,7.0,9,480308,1,99.75
116,ACME-WS-UVF,conhost.exe,2,0.0,0,2,2,0.00
117,ACME-WS-UVF,ntoskrnl.exe,1,7.0,8,100105,1,100.00